### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by ArcticEcho** [SOBotics/SharpExchange#10]
We need some documentation on how to use the library.

**Comment by Regenhardt** [comment]
Currently trying to build my own chat bot using this library, and can confirm I'd love to have some documentation on the different APIs.

**Comment by ArcticEcho** [comment]
I totally forgot about this, my bad. Realistically this isn't going to happen anytime soon now, I'm pretty busy nowadays. However, if you've found a bug or just need a hand, feel free to open up an issue and I'll get back to you.

**Comment by Regenhardt** [comment]
Could I add some myself to APIs I understand, and open a pull request so you can look it over and possibly add it?  
Same goes for updates, could I open a PR to update to Core 3.0 now it's released?

**Comment by ArcticEcho** [comment]
Sure! That would be greatly appreciated.

**Comment by ArcticEcho** [comment]
(Side note: we are technically targeting .NET Standard, not .NET Core specifically. So whatever the equivalent version of .NET Core 3.0 is in .NET Standard would have to be used.)

**Comment by Regenhardt** [comment]
Right, I meant netstandard, core is just what the examples will use :)
