### ISSUE TITLE
Can't make a ChatEventDataProcessor targetting multiple EventTypes

### ISSUE THREAD

**Issue by Regenhardt** [SOBotics/SharpExchange#17]
So I wanted to create my own processor that reacts to MessagePosted and MessageEdited, so I put this at the top:

`public override EventType Event { get; } = EventType.MessagePosted | EventType.MessageEdited;`

After like half an hour debugging, I realize those aren't actually flags.

Can we make them flags, so they are combinable? Or is the plan like "add the existing processor classes and subscribe to the events you want to process"?

**Comment by Regenhardt** [comment]
I'd make it flags, make the "AllEvents" int.MaxValue, and then in the router just ask (event_type & Event)

**Comment by ArcticEcho** [comment]
I had originally designed the system to have one processor per event, hence the lack of flags support. However you raise a good point, I think this would be a good addition to the event system. I'll aim to start working on this some time next week, the event system was due an update anyway I guess.

**Comment by ArcticEcho** [comment]
I was unable to make the `EventType` enumeration support flags, so we're just going to have to put up with using an [array of `EventType`s](https://github.com/SOBotics/SharpExchange/blob/master/SharpExchange/Chat/Events/ChatEventDataProcessor.cs#L9) instead. Besides that minor issue, everything else has been implemented as requested.
