### ISSUE TITLE
Is this on nuget.org?

### ISSUE THREAD

**Issue by gunr2171** [SOBotics/SharpExchange#4]
It would be really nice if it was.

**Comment by ArcticEcho** [comment]
The lib isn't available via nuget just yet. I'd like to get a few things finished before publishing the lib, such as:

 - [x] Completing #2,
 - [ ] Adding websocket support for win7 machines,
 - [ ] Getting some basic docs up for popular functions/classes. 

Chat-wise, the lib is practically finished. So, if those are the only functions you need to use, you could always add this repo as a submodule to your project.

**Comment by gunr2171** [comment]
\o/

**Comment by ArcticEcho** [comment]
\o/

Win7 support isn't a major issue right now (afaik), and who needs docs, right? I'll get that stuff done at a later date. :)
